AWSTemplateFormatVersion: '2010-09-09'
Description: Nightscout EC2 - Free Tier + Dynu Auto IP Update + SSL

Parameters:

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nome do KeyPair para SSH

  InstanceType:
    Type: String
    Default: t2.micro

  DomainName:
    Type: String
    Description: Dominio Dynu (ex: seudominio.dynu.net)

  DynuUsername:
    Type: String
    NoEcho: true

  DynuPassword:
    Type: String
    NoEcho: true

  MongoConnection:
    Type: String
    NoEcho: true

  ApiSecret:
    Type: String
    NoEcho: true


Resources:

  NightscoutSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir HTTP HTTPS SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0


  NightscoutInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SecurityGroups:
        - !Ref NightscoutSecurityGroup
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2023 (verificar região)

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y

          dnf install -y docker nginx certbot python3-certbot-nginx bind-utils --allowerasing

          systemctl enable docker
          systemctl start docker

          # Rodar Nightscout
          docker run -d \
            --name nightscout \
            -p 1337:1337 \
            -e AUTH_DEFAULT_ROLES=denied \
            -e API_SECRET=${ApiSecret} \
            -e MONGO_CONNECTION=${MongoConnection} \
            nightscout/cgm-remote-monitor:latest

          # Configurar Nginx
          cat > /etc/nginx/conf.d/nightscout.conf <<EOF
          server {
              listen 80;
              server_name ${DomainName};

              location / {
                  proxy_pass http://localhost:1337;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
              }
          }
          EOF

          systemctl enable nginx
          systemctl restart nginx

          # Script inteligente Dynu
          cat > /usr/local/bin/update-dynu.sh <<EOF
          #!/bin/bash

          HOST="${DomainName}"
          USER="${DynuUsername}"
          PASS="${DynuPassword}"

          CURRENT_IP=\$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
          DNS_IP=\$(dig +short \$HOST | tail -n1)

          if [ "\$CURRENT_IP" != "\$DNS_IP" ]; then
            echo "IP mudou. Atualizando Dynu..."
            curl -s "https://api.dynu.com/nic/update?hostname=\$HOST&myip=\$CURRENT_IP" \
              --user "\$USER:\$PASS"
          else
            echo "IP já correto."
          fi
          EOF

          chmod +x /usr/local/bin/update-dynu.sh

          # Executa na inicialização
          /usr/local/bin/update-dynu.sh

          # Cron a cada 5 minutos
          echo "*/5 * * * * root /usr/local/bin/update-dynu.sh >> /var/log/dynu.log 2>&1" > /etc/cron.d/dynu-update

          # Emitir SSL automaticamente
          certbot --nginx --non-interactive --agree-tos -m admin@${DomainName} -d ${DomainName} || true
